### ISSUE TITLE
Problem setting up devcontainer

### ISSUE THREAD

**Issue by mwoodpatrick** [qdm12/godevcontainer#39]
I'm trying to use this tool on WSL-2 (arch linux distro) I'm running the command:

` docker run -it --rm -v "/mnt/wsl/projects/git/golang/golang-examples/devctest:/repository" qmcgaw/devtainr:v0.2.0 -dev go -path /mnt/wsl/projects/git/golang/golang-examples/devctest -name devctest`

and am getting:

```
🤖 Version v0.2.0 (commit 61fc96e built on 2021-01-03T21:37:06Z)
📁 Creating .devcontainer directory...❌
mkdir /mnt/wsl/projects/git/golang/golang-examples/devctest/.devcontainer: no such file or directory
```

There is an empty directory at the path specified:

```
 ls -al /mnt/wsl/projects/git/golang/golang-examples/devctest/
total 8
drwxr-xr-x 2 mwoodpatrick mwoodpatrick 4096 Oct 15 07:05 .
drwxr-xr-x 6 mwoodpatrick mwoodpatrick 4096 Oct 15 07:05 ..
```
If I run the reported failing command it works correctly.

Any suggestions on what I'm doing wrong?

**Comment by fromz** [comment]
I think the -path parameter should be where it's mounted in the container. In your case, that would be /repository

**Comment by qdm12** [comment]
Yes that's correct, that's why it's complaining. It only creates the directory `.devcontainer` in an existing directory, otherwise it errors. thanks again @fromz - also mega sorry for the year of delay answering 😄
