### ISSUE TITLE
Using go 1.16rc1?

### ISSUE THREAD

**Issue by AAAstorga** [qdm12/godevcontainer#7]
Hello,

I recently picked up a Mac mini with the new M1 chip and I'm trying to get my setup working. On my intel based Mac, everything works fine with this + vscode remote containers. I am looking to upgrade the go version used in this repo to be 1.16rc1. Do you know exactly what I would need to change to accomplish this?

I appreciate any help! 😄

**Comment by qdm12** [comment]
Hello!

As Go 1.16 is right around the corner, I'll update the image to use Go 1.16 quite soon.

But if you're impatient, fear not, you should be able to build it yourself easily! Provided you have docker (duh) and `git` installed, just use:

```sh
docker build -t qmcgaw/godevcontainer --build-arg GO_VERSION=1.16rc1 -f alpine.Dockerfile https://github.com/qdm12/godevcontainer.git
```

Note however that this can only build an image for amd64 for now, which should be fine with the emulation amd64 <-> arm for the M1 chip & docker desktop I think. Let me know if you would be interested in running an arm64 image.
